Adjust package installation for openSUSE
On SUSE family distros the squash-tools are simply part of the
main package called "squashfs", so install that one instead. Without
this change bindep on SUSE hosts fails with:

  ERROR: These requested packages were not installed:
  squashfs-tools

Also adjust install_test_deps.sh to install required packages
on an openSUSE host.

Change-Id: I61dcd5314e78dbb1fb31e723799374edd456da99